sudo: required
dist: xenial

addons:
  chrome: stable

language: node_js
node_js:
  - '6.9'

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - gem install hiptest-publisher

before_script:
  - npm install
  - hiptest-publisher --config-file=protractor.conf --token=$SECRET_TOKEN --test-run-id=52538 --only=tests

script:
  - (npm start > /dev/null &) && (npm run protractor)

after_script:
  - hiptest-publisher --config-file=protractor.conf --token=$SECRET_TOKEN --test-run-id=52538 --push="test-reports/*.xml"
