sudo: required
dist: trusty

language: node_js
node_js:
  - '6.9'

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable
  - gem install hiptest-publisher

before_script:
  - npm install
  - hiptest-publisher --config-file=protractor.conf --token=$SECRET_TOKEN --test-run-id=52538 --only=tests

script:
  - (npm start > /dev/null &) && (npm run protractor)

after_script:
  - hiptest-publisher --config-file=protractor.conf --token=$SECRET_TOKEN --test-run-id=52538 --push="test-reports/*.xml"